//go:build linux

package ebpf

// CgroupLatency is the higher-level Go representation of a run-queue latency
// histogram for one cgroup, after the per-CPU copies have been summed over a
// single read interval. The raw per-CPU struct (schedSchedHist) is generated by
// bpf2go from the C definition.
type CgroupLatency struct {
	CgroupID uint64
	Slots    []uint64 // log2 histogram of run-queue latency (µs)
	TotalUs  uint64   // summed latency, for mean
	Count    uint64   // number of events
}

// CgroupCPUTime is the on-CPU time a cgroup consumed in one read interval, after
// summing the per-CPU copies. This is the offender signal — divide by the total
// across all cgroups to get the cgroup's CPU intensity.
type CgroupCPUTime struct {
	CgroupID uint64
	OnCpuNs  uint64
}

// Timeline geometry — must match NUM_BUCKETS / BUCKET_NS in sched_monitor.bpf.c.
const (
	TimelineBuckets  = 50              // 50 windows
	TimelineBucketNs = 100_000_000     // 100ms each → a rolling 5s ring
)

// CgroupTimeline is one cgroup's sub-interval timeline (issue #4), drained and
// re-aligned from the per-CPU ring each interval. Every slice has length
// TimelineBuckets and is ordered oldest→newest over a window ending "now", with
// the SAME epoch axis across all cgroups — so an offender's CpuNs series and a
// victim's RunqLatNs series (different cgroups) line up bucket-for-bucket and can
// be fed straight into metrics.Correlate. Empty/stale windows are zero-filled.
type CgroupTimeline struct {
	CgroupID  uint64
	RunqLatNs []uint64 // VICTIM: summed run-queue wait per bucket
	RunqCount []uint64 // run-queue waits per bucket (activity gate)
	CpuNs     []uint64 // OFFENDER: on-CPU time per bucket
	CtxSwitch []uint64 // on-CPU slices per bucket (activity gate)
}

// CgroupBlkio is the block-I/O latency histogram + throughput for one cgroup
// over a read interval, after summing the per-CPU copies.
type CgroupBlkio struct {
	CgroupID uint64
	Slots    []uint64 // log2 histogram of I/O latency (µs)
	TotalUs  uint64   // summed latency, for the mean
	Count    uint64   // completed requests (ops)
	Bytes    uint64   // total bytes moved
}

// CgroupNet is the network counters for one cgroup over a read interval, after
// summing the per-CPU copies.
type CgroupNet struct {
	CgroupID    uint64
	Retransmits uint64 // TCP segments retransmitted (victim signal)
	TxBytes     uint64 // bytes handed to TCP for sending (offender signal)
	TxSegs      uint64 // number of sendmsg calls
}
