//go:build linux

package ebpf

// CgroupLatency is the higher-level Go representation of a run-queue latency
// histogram for one cgroup, after the per-CPU copies have been summed over a
// single read interval. The raw per-CPU struct (schedSchedHist) is generated by
// bpf2go from the C definition.
type CgroupLatency struct {
	CgroupID uint64
	Slots    []uint64 // log2 histogram of run-queue latency (µs)
	TotalUs  uint64   // summed latency, for mean
	Count    uint64   // number of events
}
