//go:build linux

package ebpf

// CgroupLatency is the higher-level Go representation of a run-queue latency
// histogram for one cgroup, after the per-CPU copies have been summed over a
// single read interval. The raw per-CPU struct (schedSchedHist) is generated by
// bpf2go from the C definition.
type CgroupLatency struct {
	CgroupID uint64
	Slots    []uint64 // log2 histogram of run-queue latency (µs)
	TotalUs  uint64   // summed latency, for mean
	Count    uint64   // number of events
}

// CgroupCPUTime is the on-CPU time a cgroup consumed in one read interval, after
// summing the per-CPU copies. This is the offender signal — divide by the total
// across all cgroups to get the cgroup's CPU intensity.
type CgroupCPUTime struct {
	CgroupID uint64
	OnCpuNs  uint64
}

// CgroupBlkio is the block-I/O latency histogram + throughput for one cgroup
// over a read interval, after summing the per-CPU copies.
type CgroupBlkio struct {
	CgroupID uint64
	Slots    []uint64 // log2 histogram of I/O latency (µs)
	TotalUs  uint64   // summed latency, for the mean
	Count    uint64   // completed requests (ops)
	Bytes    uint64   // total bytes moved
}

// CgroupNet is the network counters for one cgroup over a read interval, after
// summing the per-CPU copies.
type CgroupNet struct {
	CgroupID    uint64
	Retransmits uint64 // TCP segments retransmitted (victim signal)
	TxBytes     uint64 // bytes handed to TCP for sending (offender signal)
	TxSegs      uint64 // number of sendmsg calls
}
